Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -10,9 +10,8 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-- name: Checkout code
-        uses: actions/checkout@v2
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-- name: Run failing test
-        run: echo "Failing test" && 
-  exit 1
+    - name: Run failing test
+      run: echo "Failing test" && exit 1
